apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 8
      index: "*"
      timeField: "@timestamp"
      logMessageField: "msg"
      # בטל time-based index pattern:
      # מחק לגמרי או השאר ריק. העיקר שלא יהיה "1m"
      # interval: ""
      # (אופציונלי) min time interval לאגרגציות:
      timeInterval: "10s"

