filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      include_containers:
        - "node-consumer"   # שם הקונטיינר שלך
      templates:
        - condition:
            contains:
              docker.container.name: "tidb-cdc-stack-node-consumer-1"
          config:
            - type: filestream
              enabled: true
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              parsers:
                - container:
                    type: docker
                    target: "json"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
