filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      include_containers:
        - "node-consumer"
      templates:
        - condition:
            contains:
              docker.container.name: "tidb-cdc-stack-node-consumer-1"
          config:
            - type: filestream
              enabled: true
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              parsers:
                - container:
                    type: docker
                    target: "json"
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    target: "cdc"
                    overwrite_keys: true
                - drop_fields:
                    fields: ["log", "stream", "container", "docker", "input", "ecs", "host", "agent"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
